

apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iot-bonus
servers: 1
agents: 0
ports:
  - port: 8888:8888
    nodeFilters:
      - loadbalancer
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 8080:8000
    nodeFilters:
      - loadbalancer

