apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: php:8.2-apache
        env:
        - name: APP_NAME
          value: "app1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POP_ID
          value: "pop-app1"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-assets
          mountPath: /var/www/html
      volumes:
      - name: app-assets
        configMap:
          name: app-shared-assets
          items:
          - key: index.php
            path: index.php
          - key: main.css
            path: main.css
          - key: Kubernetes.svg
            path: images/Kubernetes.svg
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP