Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.define "dagudeloS" do |control|
        control.vm.box = "debian/bookworm64"
        control.vm.hostname = "dagudeloS"
        control.vm.network "private_network", ip: "192.168.56.110", primary: true
        control.vm.provision "shell", path: "scripts/server.sh"
        control.vm.provision "shell", path: "scripts/deploy_apps.sh"
        control.vm.provider "libvirt" do |provider|
            provider.memory = 2048
            provider.cpus = 4
            provider.driver = "kvm"
            provider.machine_type = "pc"
            provider.uri = "qemu:///system"
        end
    end
end